import AcUnitIcon from '@mui/icons-material/AcUnit';
import Navbar from '../components/navbar/Navbar';
import "./home.scss";

const Home = () => {
  return (
    <div className="home">
        <Navbar />

        <img width="100%" src="https://images.pexels.com/photos/6899260/pexels-photo-6899260.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500" />

        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique itaque reprehenderit, sed modi magni inventore laborum cum alias exercitationem fuga aliquid officiis accusamus. Adipisci magnam iure maxime similique! Ipsa, voluptatum.
        
    </div>
  )
}

export default Home
